version: '3.4'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - 3306:3306
  sword-task-api:
    image: sword-task-api
    build: ./app
    env_file: ./app/.env
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    environment:
      DATABASE_URL: $DATABASE_URL
    stdin_open: true
    tty: true

volumes:
  db:
