version: '3.4'

services:
  swordtaskapi:
    image: swordtaskapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3000:3000
  db:
    image: mysql:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prisma
