version: '3.4'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: health
      MYSQL_DATABASE: sword
      MYSQL_USER: sword
      MYSQL_PASSWORD: health
    ports:
      - 3306:3306
  sword-task-api:
    image: sword-task-api
    build: ./app
    env_file: ./app/.env
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    environment:
      - DATABASE_URL=$DATABASE_URL
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
