version: '3.4'

services:
  mysqldb-test:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3307:3306
  sword-task-api:
    image: sword-task-api
    build: ./app
    env_file: ./app/.env.test
    ports:
      - 3000:3000
    depends_on:
      - mysqldb-test
    environment:
      DATABASE_URL: $DATABASE_URL
    stdin_open: true
    tty: true

volumes:
  db:
